# Generated by Django 5.2.11 on 2026-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('UNTRACKED', 'پیگیری نشده'), ('FAILED', 'ناموفق'), ('SHIPPING', 'در حال ارسال'), ('SHIPPED', 'ارسال شده')], default='UNTRACKED', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'پرداخت نشده'), ('PAID', 'پرداخت شده'), ('FAILED', 'ناموفق')], default='UNPAID', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'ایجاد شده'), ('REQUIRES_PAYMENT', 'نیازمند پرداخت'), ('COMPLETED', 'تکمیل شده')], default='CREATED', max_length=32),
        ),
    ]
